// flow-typed signature: dc22029ea201352f55381e5dde584cab
// flow-typed version: <<STUB>>/gulp-nodemon_v^2.4.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-nodemon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-nodemon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-nodemon/Gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-nodemon/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-nodemon/Gulpfile.js' {
  declare module.exports: $Exports<'gulp-nodemon/Gulpfile'>;
}
declare module 'gulp-nodemon/index' {
  declare module.exports: $Exports<'gulp-nodemon'>;
}
declare module 'gulp-nodemon/index.js' {
  declare module.exports: $Exports<'gulp-nodemon'>;
}
declare module 'gulp-nodemon/server.js' {
  declare module.exports: $Exports<'gulp-nodemon/server'>;
}
