// flow-typed signature: e72d47fb3b63f351c650f64a64d02a68
// flow-typed version: <<STUB>>/session-file-store_v^1.2.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'session-file-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'session-file-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'session-file-store/lib/reap-worker' {
  declare module.exports: any;
}

declare module 'session-file-store/lib/session-file-helpers' {
  declare module.exports: any;
}

declare module 'session-file-store/lib/session-file-store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'session-file-store/index' {
  declare module.exports: $Exports<'session-file-store'>;
}
declare module 'session-file-store/index.js' {
  declare module.exports: $Exports<'session-file-store'>;
}
declare module 'session-file-store/lib/reap-worker.js' {
  declare module.exports: $Exports<'session-file-store/lib/reap-worker'>;
}
declare module 'session-file-store/lib/session-file-helpers.js' {
  declare module.exports: $Exports<'session-file-store/lib/session-file-helpers'>;
}
declare module 'session-file-store/lib/session-file-store.js' {
  declare module.exports: $Exports<'session-file-store/lib/session-file-store'>;
}
